# the error that means that the user to whom
# the event invitation was sent cannot be invited
THIS_USER_CAN_NOT_BE_INVITED: dict[str, str] = {"error": "this_user_cannot_be_invited"}
ALREADY_SENT_REQUEST_TO_THIS_USER_IN_FRIENDS: dict[str, str] = {"error": "already_sent_request_to_this_user_in_friends"}

# the  error that means that the user cannot invite himself to the event
CAN_NOT_INVITE_YOURSELF_TO_FRIENDS: dict[str, str] = {"error": "cant_invite_yourself_to_friends"}
